Clean up mail oauth script.

diff --git a/scripts/bin/oauth-response b/scripts/bin/oauth-response
--- a/scripts/bin/oauth-response
+++ b/scripts/bin/oauth-response
@@ -9,17 +9,20 @@
 # Sasl xoauth2 plugin
 # https://github.com/moriyoshi/cyrus-sasl-xoauth2
 
-AUTHURL='https://login.microsoftonline.com/913f18ec-7f26-4c5f-a816-784fe9a58edd/oauth2/v2.0/authorize'
+# Can also be set to 'common'
+TENANT='913f18ec-7f26-4c5f-a816-784fe9a58edd'
+
+AUTHURL="https://login.microsoftonline.com/$TENANT/oauth2/v2.0/authorize"
 CLIENT_ID='6731de76-14a6-49ae-97bc-6eba6914391e'
 
-TOKENURL='https://login.microsoftonline.com/913f18ec-7f26-4c5f-a816-784fe9a58edd/oauth2/v2.0/token'
+TOKENURL="https://login.microsoftonline.com/$TENANT/oauth2/v2.0/token"
 SECRET='JqQX2PNo9bpM0uEihUPzyrh'
 
 SCOPE='offline_access%20https://outlook.office.com/IMAP.AccessAsUser.All'
 #REDIR_URI='http%3A//localhost/myapp/'
 
-
-PASSPATH=automation/liu-imap
+export PASSWORD_STORE=${PASSWORD_STORE:-$HOME/.password-store}
+PASSBASE=automation/
 
 get_free_port() {
 	for p in {8080..9000}; do
@@ -49,13 +52,14 @@ get_token() {
 		--data "scope=$SCOPE" \
 		--data "redirect_uri=$REDIR_URI" \
 		--data 'grant_type=authorization_code' \
-		--data "client_secret=$SECRET" \
-		| pass insert --multiline --force $PASSPATH
+		--data "client_secret=$SECRET"
 }
 
-get_refresh_token() {
+refresh_refresh_token() {
 
+	# refresh token could be gotten here since we know token name
 	refresh_token=$1
+	token_name=$2
 
 	curl -X POST "$TOKENURL" \
 		--data "client_id=$CLIENT_ID" \
@@ -63,7 +67,7 @@ get_refresh_token() {
 		--data "refresh_token=$refresh_token" \
 		--data 'grant_type=refresh_token' \
 		--data "client_secret=$SECRET" \
-		| pass insert --multiline --force $PASSPATH
+		| pass insert --multiline --force $PASSBASE/$token_name
 }
 
 # generate xoauth2 token (will be done by sasl)
@@ -78,7 +82,10 @@ write_xoauth2_token() {
 # 1 AUTHENTICATE XOAUTH2 ^^
 
 new_token() {
-	# echo "== Getting brand new token =="
+
+	token_name=$1
+
+	echo "== Getting brand new token ==" > /dev/stderr
 
 	tmpfile=$(mktemp)
 
@@ -88,32 +95,38 @@ new_token() {
 	get_authentication_code
 	wait $pid
 	. $tmpfile
-	get_token $code
+	get_token $code | pass insert --multiline --force $PASSBASE/$token_name
 
-	# rm $tmpfile
+	rm $tmpfile
 }
 
 main () {
+	token_name=$1
 
-	if `pass $PASSPATH > /dev/null 2>&1`; then
-		refresh_token=$(pass $PASSPATH | jq -r '.refresh_token')
+	if `pass $PASSBASE/$token_name > /dev/null 2>&1`; then
+		refresh_token=$(pass $PASSBASE/$token_name | jq -r '.refresh_token')
 
 		if [ "x$refresh_token" = 'xnull' -o "x$refresh_token" = 'x' ]; then
 			new_token
 		else
-			password_store=${PASSWORD_STORE:-$HOME/.password-store}
-			elapsed=$[ `date +%s` - `stat $password_store/$PASSPATH.gpg -c '%Y'` ]
-			# 3599 should be checked from the $PASSPATH file...
+			elapsed=$[ `date +%s` - `stat "$PASSWORD_STORE/$PASSBASE/$token_name.gpg" -c '%Y'` ]
+			# 3599 should be checked from the token file...
 			if [ $elapsed -gt 3599 ]; then
-				# echo "== Refreshing old token =="
-				get_refresh_token $refresh_token
+				echo "== Refreshing old token ==" > /dev/stderr
+				refresh_refresh_token $refresh_token $token_name
 			else
-				: # echo "token still good"
+				echo "token still good" > /dev/stderr
 			fi
 		fi
 	else
-		new_token
+		new_token $token_name
 	fi
 }
 
-main
+token_name=$1
+if [ "x$token_name" = "x" ]; then
+	echo "Missing token name!" > /dev/stderr
+	exit 1
+fi
+main $token_name 2> /dev/null
+pass $PASSBASE/$token_name | jq -r '.access_token'
